import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download } from "lucide-react";
import { Button } from "../ui/button";

export function DigestDetailCard() {
  const handleClick = () => {
    alert("Download PDF clicked");
    return;
  }
  return (
    <Card className="col-span-1 shadow-md">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4 bg-[hsl(var(--custom-header-bg))] text-[hsl(var(--custom-header-fg))] rounded-t-lg">
        <CardTitle className="text-xl font-bold">June 27 Digest</CardTitle>
        <Button className="flex" onClick={handleClick}>

        <Download className="flex"/>
        <a href="#" className="flex-col text-sm font-medium hover:underline" >
          Download PDF
        </a>
        </Button>
      </CardHeader>
      <CardContent className="pt-6 space-y-4">
        <div>
          <h3 className="text-2xl font-bold text-foreground">Topic 2</h3>
          <p className="text-lg text-muted-foreground">Cluster Headline</p>
          <p className="text-md text-muted-foreground">Top article title</p>
        </div>
        <div>
          <p className="font-bold text-foreground">Summary generated by GenAI</p>
          <p className="text-sm text-foreground">
            Summary generated sangas al oreem text.
          </p>
        </div>
        <a
          href="#"
          className="text-primary font-semibold hover:underline text-sm"
        >
          View Related Articles (7-day context)
        </a>
      </CardContent>
    </Card>
  );
}