name: Deploy to AWS Amplify (Manual)

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repository (e.g. user/repo-name)'
        required: true
      branch:
        description: 'Branch to deploy (e.g. main)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (if needed)
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip boto3

      - name: Set Env Variales
        run: |
          GITHUB_PAT=$(aws secretsmanager get-secret-value \
            --secret-id github_pat \
            --query SecretString \
            --output text)

          # If your secret is a JSON, extract the actual value
          # GITHUB_PAT=$(echo "$GITHUB_PAT" | jq -r .github_pat)

          echo "GITHUB_PAT=$GITHUB_PAT" >> $GITHUB_ENV
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAT5VEV4FHFQQJBZVX
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Run Amplify Deployment Script
        run: |
          python amplify.py "${{ github.event.inputs.repo }}" "${{ github.event.inputs.branch }}"
