name: Deploy API Gateway

on:
  push:
    branches: [main, api]

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run API deployment script
        env:
          AWS_ACCESS_KEY_ID: AKIAT5VEV4FHFQQJBZVX
          AWS_SECRET_ACCESS_KEY: o56LCVEDcTPD8RgU2iWtz8SBklKa5DqQ6+nCYawf
          AWS_REGION: us-east-1          # or your region
        run: |
          python3 api/deploy-api.py
