name: Build Lambda Layer

on:
  push:
    branches: [main, automation]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # match your Lambda runtime

      - name: Install dependencies to python/
        run: |
          mkdir -p python
          pip install -r backend/requirements.txt -t python/

      - name: Zip the layer
        run: zip -r layer.zip python

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAT5VEV4FHFQQJBZVX
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Publish Lambda Layer
        run: |
          LAYER_NAME="my-python-layer"
          RUNTIME="python3.11"

          aws lambda publish-layer-version \
            --layer-name "$LAYER_NAME" \
            --description "Dependencies from backend/requirements.txt" \
            --zip-file fileb://layer.zip \
            --compatible-runtimes "$RUNTIME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-layer
          path: layer.zip