name: Build Lambda Layer

on:
  push:
    branches: [main, automation]
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust to your Lambda runtime

      - name: Create python directory for layer
        run: mkdir -p python

      - name: Install dependencies to python/
        run: |
          pip install -r backend/requirements.txt -t python/

      - name: Zip the layer
        run: zip -r layer.zip python

      - name: Upload layer artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-layer
          path: layer.zip
