name: Build Lambda Layers

on:
  push:
    paths:
      - 'backend/layers/**'
  workflow_dispatch:

jobs:
  build-and-publish-layers:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: hackathon-lambda-ap-ai-cyberark
      PYTHON_VERSION: python3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAT5VEV4FHFQQJBZVX
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Build and publish each layer from backend/layers/
        run: |
          mkdir -p layer_zips
          
          for dir in backend/layers/*; do
            if [ -f "$dir/requirements.txt" ]; then
              LAYER_NAME=$(basename "$dir")
              echo "🔧 Building layer: $LAYER_NAME"

              rm -rf "$dir/python"
              mkdir -p "$dir/python"

              pip install --upgrade --no-cache-dir -r "$dir/requirements.txt" -t "$dir/python"

              find "$dir/python" -type d -name "__pycache__" -exec rm -rf {} +
              find "$dir/python" -type d -name "tests" -exec rm -rf {} +
              find "$dir/python" -type f -name "*.pyc" -delete
              find "$dir/python" -type d -name "*.dist-info" -exec rm -rf {} +

              ZIP_PATH="layer_zips/${LAYER_NAME}.zip"

              echo "📦 Zipping to $ZIP_PATH"
              cd "$dir"
              zip -r "../../${ZIP_PATH}" python > /dev/null
              cd - > /dev/null

              echo "📤 Uploading $ZIP_PATH to S3"
              aws s3 cp "$ZIP_PATH" s3://$S3_BUCKET/layers/${LAYER_NAME}.zip

              echo "🚀 Publishing layer: $LAYER_NAME"
              LAYER_ARN=$(aws lambda publish-layer-version \
                --layer-name "$LAYER_NAME" \
                --description "Lambda layer for $LAYER_NAME" \
                --content S3Bucket=$S3_BUCKET,S3Key=layers/${LAYER_NAME}.zip \
                --compatible-runtimes $PYTHON_VERSION \
                --query 'LayerVersionArn' --output text)

              echo "✅ Published $LAYER_NAME: $LAYER_ARN"
            fi
          done