name: Build Lambda Layers

on:
  push:
    paths:
      - 'backend/layers/**'
  workflow_dispatch:

jobs:
  build-and-publish-layers:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: hackathon-lambda-ap-ai-cyberark
      PYTHON_VERSION: python3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAT5VEV4FHFQQJBZVX
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Build and publish each layer from backend/layers/
        run: |
          for dir in backend/layers/*; do
            if [ -f "$dir/requirements.txt" ]; then
              LAYER_NAME=$(basename "$dir")
              echo "🔧 Building layer: $LAYER_NAME"

              # Clean old build (if any) and recreate
              rm -rf "$dir/python"
              mkdir -p "$dir/python"

              # Install dependencies
              pip install --upgrade --no-cache-dir -r "$dir/requirements.txt" -t "$dir/python"

              # Clean unnecessary files
              find "$dir/python" -type d -name "__pycache__" -exec rm -rf {} +
              find "$dir/python" -type d -name "tests" -exec rm -rf {} +
              find "$dir/python" -type f -name "*.pyc" -delete
              find "$dir/python" -type d -name "*.dist-info" -exec rm -rf {} +

              # Zip the layer
              zip_path="${LAYER_NAME}.zip"
              cd "$dir"
              zip -r "../../${zip_path}" python > /dev/null
              cd - > /dev/null

              # Upload to S3
              echo "📤 Uploading $zip_path to S3"
              aws s3 cp "$zip_path" s3://$S3_BUCKET/layers/$zip_path

              # Publish the Lambda layer
              echo "🚀 Publishing layer: $LAYER_NAME"
              LAYER_ARN=$(aws lambda publish-layer-version \
                --layer-name "$LAYER_NAME" \
                --description "Lambda layer for $LAYER_NAME" \
                --content S3Bucket=$S3_BUCKET,S3Key=layers/$zip_path \
                --compatible-runtimes $PYTHON_VERSION \
                --query 'LayerVersionArn' --output text)

              echo "✅ Published $LAYER_NAME: $LAYER_ARN"

              # Optionally remove the zip after upload
              rm -f "$zip_path"
            fi
          done

